apiVersion: batch/v1
kind: CronJob
metadata:
  name: finans-daily-snapshot
  namespace: default
spec:
  # TR Saati ile 22:00 (UTC 19:00)
  schedule: "0 19 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: snapshot-curl
            image: curlimages/curl:latest
            env:
            - name: TZ
              value: "Europe/Istanbul"
            args:
            - -X
            - POST
            # DÜZELTİLEN YER: Servis adı 'finans-backend-service' olarak değiştirildi
            - http://finans-backend-service:8000/system/daily-job
          restartPolicy: OnFailure
