apiVersion: batch/v1
kind: CronJob
metadata:
  name: finans-daily-snapshot
  namespace: default
spec:
  # TR Saati ile 23:59 (UTC 20:59)
  schedule: "59 20 * * *"
  successfulJobsHistoryLimit: 3 # Geçmişteki başarılı 3 kaydı loglarda tutar
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: snapshot-curl
            image: curlimages/curl:latest
            # Backend servisinin adı k8s yaml dosyasındaki service adına (finans-backend) göre düzenlenmiştir
            args:
            - -X
            - POST
            - http://finans-backend:8000/system/daily-job
          restartPolicy: OnFailure

